INSERT INTO ROLES (CODE, NAME) VALUES ('MANAGER', 'Manager');
INSERT INTO ROLES (CODE, NAME) VALUES ('STUDENT', 'Student');
INSERT INTO ROLES (CODE, NAME) VALUES ('TUTOR', 'Tutor');
INSERT INTO ROLES (CODE, NAME) VALUES ('ADMIN', 'Admin');
